### ISSUE TITLE
Add Export Button to Subunit Page

### ISSUE THREAD

**Issue by baileyrosato** [baileyrosato/Anatomia#88]
Implement export feature using Material UI.

**Comment by baileyrosato** [comment]
Team is looking into using whiteboard for interactivity. Waiting for updates on implementation to adjust necessary exporting features.

**Comment by baileyrosato** [comment]
Nicole was able to figure out how to export as a PNG!

**Comment by nicolesylvester** [comment]
2/28: Will be implemented in PR #125
