### ISSUE TITLE
Add exit button to sidebar menu

### ISSUE THREAD

**Issue by nicolesylvester** [baileyrosato/Anatomia#96]
When the screen size is small, the user cannot get out of the sidebar menu.
![Screenshot 2024-02-14 115805](https://github.com/baileyrosato/Anatomia/assets/71994185/3c312ea1-a136-4c01-834a-aa9c838572cc)

- maybe add an X button to close menu

**Comment by baileyrosato** [comment]
Main menu added to sidebar menu 2/20/24
